### ISSUE TITLE
"always" tags breaking usage of other tags

### ISSUE THREAD

**Issue by kelvan** [rbicker/ansible-nextcloud#28]
I'm trying to use this role together with another role and added tags for both role_includes.
```
tasks:                                                                        
    - import_role:                                                              
        name: ansible-nextcloud                                                 
      tags:                                                                     
        - nextcloud                                                             
                                                                                
    - import_role:                                                              
        name: collabora                                                         
      tags:                                                                     
        - collabora
```
running the playbook with `--tags collabora` fails as one of the `always` tasks depend on an other task without `always`:
```
FAILED! => {"msg": "The conditional check 'new_installation.changed' failed. The error was: error while evaluating conditional (new_installation.changed): 'new_installation' is undefined ...
```
