### ISSUE TITLE
Syntax error in nextcloud_config_options example?

### ISSUE THREAD

**Issue by evoncken** [rbicker/ansible-nextcloud#40]
I'm probably overlooking something.
I tried to add config options as per the example, but Ansible 2.10.4 keeps complaining about the syntax.

    Syntax Error while loading YAML.
      did not find expected node content
    
              nextcloud_config_options:
                - { option: overwrite.cli.url, value: "'https://nc-demo.example.com'" }
                ^ here

This is my playbook for context:

    - hosts: all
      gather_facts: yes
      become: yes
      roles:
        - { role: rbicker.nextcloud,
                  nextcloud_domain: nc-demo.hosting.example.com,
                  nextcloud_version: latest-20,
                  nextcloud_use_https: false,
                  nextcloud_web_root:  '/var/www/virtual/nc-demo',
                  nextcloud_data_root: '/srv/nextcloud/nc-demo/data',
                  php_version: "7.4",
                  nextcloud_config_options:
                    - { option: overwrite.cli.url, value: "'https://nc-demo.example.com'" }
                    - { option: trusted.domains, value: "'webhost.example.com'" }
          }

Environment: macOS 10.15.7

    ed@BigMac:~/etc/ansible-nextcloud$ ansible --version
    ansible 2.10.4
      config file = /Users/ed/etc/ansible-nextcloud/ansible.cfg
      configured module search path = ['/Users/ed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/local/Cellar/ansible/2.10.5/libexec/lib/python3.9/site-packages/ansible
      executable location = /usr/local/bin/ansible
      python version = 3.9.1 (default, Jan  8 2021, 17:17:17) [Clang 12.0.0 (clang-1200.0.32.28)]

**Comment by lalmeras** [comment]
Your issue is related to your playbook yaml syntax.

You wrongly mix yaml block-style (structured with indentation) and flow style (structured with ``{}[]``, json-like).

The example is consistent: it uses flow syntax only for nextcloud_config_options items.

Working syntaxes:

block-style with flow style for nextcloud_config_options:
```yaml
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: rbicker.nextcloud
      nextcloud_domain: nc-demo.hosting.example.com,
      nextcloud_version: latest-20
      nextcloud_use_https: false
      nextcloud_web_root:  '/var/www/virtual/nc-demo'
      nextcloud_data_root: '/srv/nextcloud/nc-demo/data'
      php_version: "7.4"
      nextcloud_config_options:
        - { option: overwrite.cli.url, value: "'https://nc-demo.example.com'" }
        - { option: trusted.domains, value: "'webhost.example.com'" }
```

full block-style:
```yaml
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: rbicker.nextcloud
      nextcloud_domain: nc-demo.hosting.example.com
      nextcloud_version: latest-20
      nextcloud_use_https: false
      nextcloud_web_root:  '/var/www/virtual/nc-demo'
      nextcloud_data_root: '/srv/nextcloud/nc-demo/data'
      php_version: "7.4"
      nextcloud_config_options:
        - option: overwrite.cli.url
          value: "'https://nc-demo.example.com'"
        - option: trusted.domains
          value: "'webhost.example.com'"
```

consistent flow-style for rbicker.nextcloud role item:
```yaml
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: rbicker.nextcloud
      nextcloud_domain: nc-demo.hosting.example.com,
      nextcloud_version: latest-20
      nextcloud_use_https: false
      nextcloud_web_root:  '/var/www/virtual/nc-demo'
      nextcloud_data_root: '/srv/nextcloud/nc-demo/data'
      php_version: "7.4"
      nextcloud_config_options: [
        { option: overwrite.cli.url, value: "'https://nc-demo.example.com'" },
        { option: trusted.domains, value: "'webhost.example.com'" }
      ]
```
